name: Qodana Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  qodana:
    name: Run Qodana Scan
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Qodana Scan
        uses: JetBrains/qodana-action@v2024.3.4
        with:
          pr-mode: false
          upload-result: true
          args: --apply-fixes
          push-fixes: pull-request

